events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    upstream astro_node {
        server 127.0.0.1:4321;
        keepalive 64;
    }

    server {
        listen 3000;
        root /usr/share/nginx/html;

        location /_astro/ {
            alias /usr/share/nginx/html/_astro/;
            expires 1y;
            access_log off;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        location ~* \.(jpg|jpeg|png|gif|ico|svg|css|js|json|xml|map|webmanifest|woff|woff2|ttf|eot)$ {
            expires 1d;
            access_log off;
            try_files $uri =404;
        }

        location / {
            if ($request_method = POST) {
                return 418;
            }

            try_files $uri $uri/index.html @node;
        }

        location @node {
            proxy_pass http://astro_node;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        error_page 418 = @node;
    }
}
